### ISSUE TITLE
Unsupervised hisc loss is equal to zero 

### ISSUE THREAD

**Issue by lanjinraol** [neu-spiral/OpenWorldKNet#2]
I tried to run the script "mnist_hsic_semi.py", but the overall loss of unsupervised model is equal to zero. And the results are much lower than the results shown in your paper. I don't known what happens. Is there something wrong in your code? Could you help me?

**Comment by KingSpencer** [comment]
Thanks for giving feedback! I will look into this after a recent conference deadline (after October). Meanwhile, if you can send me some more details about your error, please email to zifengwang@ece.neu.edu. If there is anything wrong, I will let you know, thanks!

**Comment by lanjinraol** [comment]
1. 论文应该少做了一个消融实验：
  对比预训练模型和引入无监督hisc loss后的聚类效果，如果引入hisc loss后有提升，才能说明hisc loss 是有效的。不知作者是否有做这一部分实验。（未在论文中发现）
 2. 我在tf 1.14 keras 2.2.4环境下跑了hisc_mnist_semi的代码，测试了预训练后的模型 聚类指标和引入无监督hisc loss后模型聚类指标，两者是一样的。其原因是模型没有训练。接着我打印了无监督训练的总loss，其值为0。这个不知道是否由于tf keras版本的问题
 3. 我也尝试用pytorch实现论文的结果，在文本数据集上跑了对比实验，引入论文的方法往往导致特征聚类指标的下降，所以希望作者能够进一步提供   hisc loss的引入提高特征鲁棒性  的证明。
